import { PriceAsset } from '@/types';

// Updated Mock Data with realistic Feb 2025 market prices
export const MOCK_ASSETS: PriceAsset[] = [
  {
    id: 'usd',
    symbol: 'USD',
    nameFa: 'دلار آمریکا',
    nameEn: 'US Dollar',
    type: 'fiat',
    priceIRR: 805000,
    priceToman: 80500,
    change24h: 1.2,
    lastUpdated: new Date().toISOString(),
    source: 'nerkh.io',
  },
  {
    id: 'eur',
    symbol: 'EUR',
    nameFa: 'یورو',
    nameEn: 'Euro',
    type: 'fiat',
    priceIRR: 865000,
    priceToman: 86500,
    change24h: 0.8,
    lastUpdated: new Date().toISOString(),
    source: 'nerkh.io',
  },
  {
    id: 'gold_18k',
    symbol: 'GOLD18',
    nameFa: 'طلای ۱۸ عیار',
    nameEn: 'Gold 18K',
    type: 'gold',
    priceIRR: 51500000,
    priceToman: 5150000,
    change24h: 1.5,
    lastUpdated: new Date().toISOString(),
    source: 'nerkh.io',
  },
  {
    id: 'coin_emami',
    symbol: 'EMAMI',
    nameFa: 'سکه امامی',
    nameEn: 'Emami Coin',
    type: 'gold',
    priceIRR: 585000000,
    priceToman: 58500000,
    change24h: 1.1,
    lastUpdated: new Date().toISOString(),
    source: 'nerkh.io',
  },
  {
    id: 'coin_bahar',
    symbol: 'BAHAR',
    nameFa: 'سکه بهار آزادی',
    nameEn: 'Bahar Coin',
    type: 'gold',
    priceIRR: 555000000,
    priceToman: 55500000,
    change24h: 0.9,
    lastUpdated: new Date().toISOString(),
    source: 'nerkh.io',
  },
  {
    id: 'coin_half',
    symbol: 'HALF',
    nameFa: 'نیم سکه',
    nameEn: 'Half Coin',
    type: 'gold',
    priceIRR: 305000000,
    priceToman: 30500000,
    change24h: 0.5,
    lastUpdated: new Date().toISOString(),
    source: 'nerkh.io',
  },
  {
    id: 'coin_quarter',
    symbol: 'QUARTER',
    nameFa: 'ربع سکه',
    nameEn: 'Quarter Coin',
    type: 'gold',
    priceIRR: 185000000,
    priceToman: 18500000,
    change24h: 1.8,
    lastUpdated: new Date().toISOString(),
    source: 'nerkh.io',
  },
  {
    id: 'btc',
    symbol: 'BTC',
    nameFa: 'بیت‌کوین',
    nameEn: 'Bitcoin',
    type: 'crypto',
    priceIRR: 72000000000,
    priceToman: 7200000000,
    change24h: 2.8,
    lastUpdated: new Date().toISOString(),
    source: 'nobitex',
  },
  {
    id: 'usdt',
    symbol: 'USDT',
    nameFa: 'تتر',
    nameEn: 'Tether',
    type: 'crypto',
    priceIRR: 806000,
    priceToman: 80600,
    change24h: 0.5,
    lastUpdated: new Date().toISOString(),
    source: 'nobitex',
  },
];
